CREATE TABLE ${taskTableName} 
   (	"RES_THEMELIBID" NUMBER, 
	"RES_THEMEID" NUMBER, 
	"SYS_RESLIB" NUMBER, 
	"SYS_RESID" NUMBER, 
	"STATUS" NUMBER NOT NULL ENABLE, 
	"SYS_CREATED" TIMESTAMP (6), 
	"SYS_LASTMODIFIED" TIMESTAMP (6), 
	"SOLR_PK" VARCHAR2(100 BYTE) NOT NULL ENABLE
)
 
